### ISSUE TITLE
Conflicts with another require

### ISSUE THREAD

**Issue by nillegal** [mercuryseries/flashy#10]
When installing via composer it actually throws

`mercuryseries/flashy 1.0.4 requires illuminate/support ~5.0|~6.0|~7.0|~8.0 -> found illuminate/support[v5.0.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.`

Laravel 9 & PHP 8.x

**Comment by mercuryseries** [comment]
Solved @nillegal. Thanks
