### ISSUE TITLE
No hint path defined for [flashy].

### ISSUE THREAD

**Issue by lionnelpat** [mercuryseries/flashy#2]
Hi, Thank's for you package Flashy

i want to use it on my project but i get this error.....  No hint path defined for [flashy].

can you help me.....

**Comment by mercuryseries** [comment]
You can watch this tutorial https://www.youtube.com/watch?v=GXMLd7F9o94.

Let me know if that solves your issue.

**Comment by pierreahoble** [comment]
Moi aussi j'ail le meme probleme
je ne sais pas si c'est ma version de laravel, je suis a la dernierre version
Aider nous s'il vous plait
