### ISSUE TITLE
not compatible 

### ISSUE THREAD

**Issue by kamsiake** [mercuryseries/flashy#6]
it seems as flashy is not compatible with latest version  of laravel

**Comment by d-stephane** [comment]
Je confirme, ça ne fonctionne pas et je n'ai pas de message d'erreur visible...  
Version de Laravel utilisée : 5.8.15

**Comment by d-stephane** [comment]
Tout fonctionne après quelques bidouillages et utilisation de la version "non slim" de jQuery

**Comment by kamsiake** [comment]
Ok ok merci mon grand 

Provenance : Courrier pour Windows 10

De : d-stephane
Envoyé le :jeudi 16 mai 2019 21:36
À : mercuryseries/flashy
Cc : kamsiake; Author
Objet :Re: [mercuryseries/flashy] not compatible (#6)

Tout fonctionne après quelques bidouillages et utilisation de la version "non slim" de jQuery
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.



---
L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
https://www.avast.com/antivirus

**Comment by aureliefb** [comment]
Bonsoir,
Quels sont les bidouillages à faire pour que Flashy fonctionne avec Laravel 5.8 ?
Merci

**Comment by mercuryseries** [comment]
Quelle erreur avez-vous lors de l'installation @aureliefb ?

**Comment by aureliefb** [comment]
Je n'ai eu aucune erreur à l'installation de Flashy mais aucun message ne s'affiche après l'envoi de mon formulaire.
Visiblement, d'après ce que disait @d-stephane , Flashy n'est pas compatible avec Laravel 5.8.
Merci.

**Comment by d-stephane** [comment]
Je viens de tester avec la version 5.8.21 et tout fonctionne nickel sur un autre projet de test.
Je ne me souviens plus du tout de la première bidouille et biensur, truc con, je n'ai pas versionné mon code vu que je testai divers trucs avec Laravel.
Pour le second bidouillage, j'ai juste choppé la version complète de jQuery car apparement celle présente était différente (n° de version identique).

**Comment by d-stephane** [comment]
Après vérif, la principale bidouille c'est surtout la suppression du second argument de la fonction JS flashy() car inultile pour moi, mais je ne crois pas que cela pose problème. Je pense plutôt qu'il s'agit de jQuery. Essai de prendre une version directement proposée sur le site officiel de jQuery pour voir...
