### ISSUE TITLE
Php 8

### ISSUE THREAD

**Issue by mdeherder** [mercuryseries/flashy#8]
Add a php8 compatibility

```
 [InvalidArgumentException]
  Package mercuryseries/flashy-bundle at version  has a PHP requirement incompatible with your PHP version (8.0.0)
```

**Comment by mercuryseries** [comment]
This package is compatible with PHP 8. (This is a Laravel Package).
The Symfony Bundle (https://github.com/mercuryseries/flashy-bundle) is also now compatible with PHP 8.
Cheers!
